* Implement a PATCH endpoint for updating Name and qualificationName for Freelancer (add qualificationName as an optional column in Freelancers table).
aon-mentees/AonFreelancing pull request #20
Opened 2024-12-13 12:42 UTC by ahmed-naeem2

2024-12-14 21:02 UTC, KAJOiq commented
Please resolve your Conflict.

2024-12-14 23:29 UTC, MohammedLilo commented on Controllers/Mobile/v1/FreelancersController.cs
> +                return CustomBadRequest();
if stored freelancer is null, you must return 404. as in other endpoints.

2024-12-14 23:34 UTC, MohammedLilo commented on Controllers/Mobile/v1/FreelancersController.cs
> +            stordFreelancer.qualificationName=updateFreelancerDTO.Qualification;
nigga you are assiging the same shit twice

2024-12-14 23:35 UTC, MohammedLilo commented on Controllers/Mobile/v1/FreelancersController.cs
> +            stordFreelancer.qualificationName=updateFreelancerDTO.Qualification;
also, delete the if statement and perform the assignment directly.

2024-12-14 23:36 UTC, MohammedLilo commented on Controllers/Web/v1/FreelancersController.cs
same as mobile's version controller

2024-12-14 23:39 UTC, MohammedLilo commented on Models/DTOs/FreelancerUpdateDTO.cs
TOO MANY WHITE SPACES

2024-12-14 23:40 UTC, MohammedLilo commented on Models/DTOs/FreelancerUpdateDTO.cs
Use a name more descriptive than `FreelancerUpdateDTO`

2024-12-14 23:41 UTC, MohammedLilo reviewed
check out the comments, also don't spam white spaces everywhere, nigga

2024-12-16 07:32 UTC, Yousif-Alsheikh commented on Controllers/Mobile/v1/FreelancersController.cs
> +        [HttpPatch("Update/{id}")]
update ?

2024-12-16 07:36 UTC, Yousif-Alsheikh commented on Controllers/Mobile/v1/FreelancersController.cs
> +        public async Task<IActionResult>UpdateQualificationAndName(long id, [FromBody]UpdateFreelancerQualificationAndName updateFreelancerQualificationAndName)
edit the DTO name  "UpdateFreelancerQualificationAndName"

2024-12-16 07:40 UTC, Yousif-Alsheikh commented on Controllers/Mobile/v1/FreelancersController.cs
> +
check if the freelancer is the one edit his info.

2024-12-16 07:41 UTC, Yousif-Alsheikh commented on Controllers/Web/v1/FreelancersController.cs
> +        [HttpPatch("Update/{id}")]
"Update/{id}" ?

2024-12-16 07:41 UTC, Yousif-Alsheikh commented on Controllers/Web/v1/FreelancersController.cs
> +        public async Task<IActionResult> UpdateQualificationAndName(long id, [FromBody] UpdateFreelancerQualificationAndName freelancerUpdateDTO)
edit the DTO name "UpdateFreelancerQualificationAndName"

2024-12-16 07:41 UTC, Yousif-Alsheikh commented on Controllers/Web/v1/FreelancersController.cs
> +
check if the freelancer is the one edit his info .

2024-12-16 07:44 UTC, Yousif-Alsheikh commented on Models/DTOs/UpdateFreelancerQualificationAndName.cs
> +        public string? qualificationName { get; set; }
SpecializationName insted of qualificationName, and freelancer may have more than on specialization .

2024-12-16 07:46 UTC, Yousif-Alsheikh requested changes
please check your code again.

2024-12-16 07:46 UTC, KAJOiq commented
@ahmed-naeem2 you should check out your friends comment, so you need to update your code then push it again.

2024-12-16 13:23 UTC, closed without merging